"""empty message

Revision ID: f303a8664e16
Revises: ad0725af11f0
Create Date: 2021-08-30 12:18:17.889935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f303a8664e16'
down_revision = 'ad0725af11f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('email', sa.String(length=200), nullable=True))
    op.add_column('contact', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('contact', sa.Column('address', sa.String(length=200), nullable=True))
    op.drop_column('contact', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('contact', 'address')
    op.drop_column('contact', 'phone_number')
    op.drop_column('contact', 'email')
    # ### end Alembic commands ###
